---
- hosts: dev
  become: true
  tasks:
    - name: Install Python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the Container
      docker_container:
        name: myhtmlapp
        image: "ketuvasuops/myhtmlapp:{{DOCKER_TAG}}"
        state: started
        ports: 
          - "8083:8083"
