---
- hosts: dev
  become: True
  tasks:
    - name: Start the Container
      docker_container:
        name: myhtmlapp
        image: "ketuvasuops/myhtmlapp:{{DOCKER_TAG}}"
        state: started
        published_ports: 
            - 0.0.0.0:8083:8083
